CREATE TABLE produto(
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	preco FLOAT NOT NULL,
	marca BIGINT NOT NULL,
	precocusto FLOAT,
	quantidest FLOAT,
	ncm INT,
	codigobarra BIGINT
	
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PRODUTO ADD CONSTRAINT FK_MARCA FOREIGN KEY(MARCA) REFERENCES marca(codigo);
