CREATE TABLE compra(
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	COMPRA_PESSOA BIGINT,
	COMPRA_PRODUTO BIGINT,
	QUANTIDADE FLOAT,
	VALOR_TOTAL FLOAT,
	DESCONTO FLOAT,
	DT_COMPRA TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_PESSOA FOREIGN KEY(COMPRA_PESSOA) REFERENCES PESSOA(CODIGO);
ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_PRODUTO FOREIGN KEY(COMPRA_PRODUTO) REFERENCES PRODUTO(CODIGO);


CREATE TABLE PAGAMENTO_COMPRA(
	CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	COD_PAGAMENTO BIGINT,
	COD_COMPRA BIGINT,
	NUMCARTAO BIGINT,
	NUMBOLETO BIGINT,
	AGENCIA INT,
	VEZES INT,
	DT_EMISSAO DATE,
	DT_VENCIMENTO DATE

)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PAGAMENTO_COMPRA ADD CONSTRAINT FK_COMPRA_PAGAMENTO FOREIGN KEY(COD_PAGAMENTO) REFERENCES PAGAMENTO(CODIGO);
ALTER TABLE PAGAMENTO_COMPRA ADD CONSTRAINT FK_COMPRA_COMPRA FOREIGN KEY(COD_COMPRA) REFERENCES COMPRA(CODIGO);
