CREATE TABLE compra(
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	COMPRA_CARRINHO BIGINT(20) NOT NULL,
	DESCONTO FLOAT,
	VALORCOMDESCONTO FLOAT,
	DT_COMPRA TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE PAGAMENTO_COMPRA(
	CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	COD_PAGAMENTO BIGINT,
	COD_COMPRA BIGINT,
	NUMCARTAO BIGINT,
	NUMBOLETO BIGINT,
	AGENCIA INT,
	VEZES INT,
	DT_EMISSAO DATE,
	DT_VENCIMENTO DATE

)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PAGAMENTO_COMPRA ADD CONSTRAINT FK_COMPRA_PAGAMENTO FOREIGN KEY(COD_PAGAMENTO) REFERENCES PAGAMENTO(CODIGO);
ALTER TABLE PAGAMENTO_COMPRA ADD CONSTRAINT FK_COMPRA_COMPRA FOREIGN KEY(COD_COMPRA) REFERENCES COMPRA(CODIGO);
